services:
  mongo:
    image: mongo:6.0-jammy  
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass 
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/
    networks:
      - mongo-network
    depends_on:
      - mongo

  node-app:
    image: kiran700/nodejs-login-app:${APP_VERSION:-latest}
    container_name: node-app
    ports:
      - "3000:3000"
    networks:
      - mongo-network
    depends_on:
      - mongo

networks:
  mongo-network:
    driver: bridge
